from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone

# Create your models here.
class Tag(models.Model):
    caption = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.caption}"

    class Meta:
        verbose_name_plural = "Tags"

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email_adress = models.EmailField()

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name()

class Post(models.Model):
    title = models.CharField(max_length=45)
    type = models.CharField(max_length=150, default=None)
    image_title = models.ImageField(upload_to="posts")
    image_all_posts_360x340 = models.ImageField(upload_to="posts", null=True, blank=True)
    image_slider_360x236 = models.ImageField(upload_to="posts", null=True, blank=True)
    image_side_popular_post_300x138 = models.ImageField(upload_to="posts", null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, db_index=True)
    excerpt = models.CharField(max_length=200)
    content = models.TextField(validators=[MinLengthValidator(10)])
    content_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_1A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_1B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_1C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_1D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_1 = models.TextField(validators=[MinLengthValidator(0)],null=True,blank=True)
    list_elements_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_A1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_A2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_1 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_2A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_2B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_2C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_2D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_6 = models.TextField(validators=[MinLengthValidator(0)],null=True,blank=True)
    list_elements_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_B1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_B2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_2 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_3A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_3B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_3C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_3D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_11 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_12 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_13 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_14 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_15 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_C1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_C2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_3 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_3 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_4A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_4B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_4C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_4D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_16 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_17 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_18 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_19 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_20 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_D1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_D2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_4 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_4 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_5A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_5B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_5C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_5D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_21 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_22 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_23 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_24 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_25 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_E1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_E2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_5 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_5 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_6A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_6B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_6C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_6D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_26 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_27 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_28 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_29 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_30 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_F1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_F2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_6 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_6 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_7A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_7B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_7C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_7D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_31 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_32 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_33 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_34 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_35 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_G1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_G2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_7 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_7 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_8A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_8B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_8C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_8D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_36 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_37 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_38 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_39 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_40 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_H1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_H2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_8 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_8 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_9A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_9B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_9C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_9D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_41 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_42 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_43 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_44 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_45 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_I1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_I2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_9 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_9 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_10A = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_10B = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_10C = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    content_10D = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    link_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_46 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_47 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_48 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_49 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    list_elements_50 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_itr_description_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_J1 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_pic_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_nick_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_href_J2 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    twitter_date_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    image_in_post_10 = models.ImageField(upload_to="posts", null=True, blank=True)
    quote_10 = models.TextField(validators=[MinLengthValidator(0)], null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL,null=True, related_name="posts")
    tags = models.ManyToManyField(Tag)
    views = models.PositiveIntegerField(default=0)
# funkcja z aktywnymi linkami:
    def get_absolute_url(self):
        return reverse("detail",args=[self.slug])

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    def __str__(self):
        return f"{self.title}"

class Comment(models.Model):
    user_name = models.CharField(max_length=120, blank=False, null=False)
    user_email = models.EmailField(blank=False, null=False)
    text = models.TextField(max_length=400, blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")


class SubscribedUsers(models.Model):
    email = models.EmailField(unique=True, max_length=100)
    created_date = models.DateTimeField("Data created", default=timezone.now)

    def __str__(self):
        return f"{self.email}"
